# KeyFram estimate of grah slam, in contrast to KeyFrameRos, the transforamtion and uncertainty of the edges is marginalized into the keyframes

uint64 gid

# In a few cases separate msg files for ROS1 & ROS2 integration, see
# https://docs.ros.org/en/foxy/The-ROS2-Project/Contributing/Migration-Guide.html#message-service-and-action-definitions
builtin_interfaces/Time stamp
geometry_msgs/PoseWithCovariance estimate