# timestamp of the last received graph estimate
builtin_interfaces/Time last_stamp

---

# whether the graph has been updated since last_stamp
bool updated

# current graph estimate if updated is true
GraphEstimateRos2 graph_estimate