# timestamp of the last received cloud map
builtin_interfaces/Time last_stamp

---

# whether the map has been updated since last_stamp
bool updated

# current map as point cloud if updated is true
sensor_msgs/PointCloud2 cloud_map